# "release/": mavenBuild() -> publishJunitResult() -> deployApplication(SYS) -> sonarScan() 
#       -> newmanRegressionTest(SYS) -> codeScan() -> publishArtifacts()
##Feature BRANCH
feature:
  helloWorld:
    message: 'FEATURE BRANCH'
    agent: 'node'
  mavenBuild:
     jdk: 'jdk8'
     command: 'mvn clean install -s settings.xml'
  sonarScan:
    ignore: "YES"
